from __future__ import annotations

from typing import Protocol

from .models import CryostatState, LockinReading, VectorField


class CryostatController(Protocol):
    """Contract implemented by simulation first, then the legacy DLL adapter."""

    def read_state(self) -> CryostatState: ...

    def set_temperature(self, temperature_k: float) -> None: ...

    def ensure_temperature_control(self, enabled: bool) -> None: ...

    def set_vector_field(self, target: VectorField) -> None: ...

    def ensure_field_control(self, enabled: bool) -> None: ...

    def request_zero_field(self) -> None: ...

    def close(self) -> None: ...


class LockinController(Protocol):
    def configure_reference(self) -> None: ...

    def configure_excitation(self, voltage_v: float, frequency_hz: float) -> None: ...

    def read_harmonic(self, harmonic: int) -> LockinReading: ...

    def close(self) -> None: ...

